name: 'ChangeGuard CI Analysis'

on:
  repository_dispatch:
    types: [run-analysis]

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout ai-code-analyzer repository'
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'List files for debugging'
      run: |
        echo "Repository contents:"
        ls -la
        echo "Root cloudbuild.yaml exists:" 
        ls -la cloudbuild.yaml || echo "Not found"

    - name: 'Trigger Cloud Build'
      run: |
        gcloud builds submit . \
          --config=cloudbuild.yaml \
          --substitutions=_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},_REGION=asia-south1,_COMMIT_SHA=${{ github.event.client_payload.commit }},_PR_NUMBER=${{ github.event.client_payload.pr_number }},_REPO_NAME=${{ github.event.client_payload.repo_name }},_REPO_FULL_NAME=${{ github.event.client_payload.repo_name }}
